### ISSUE TITLE
What we want to do before we release 4.0.0

### ISSUE THREAD

**Issue by sounisi5011** [sounisi5011/package-version-git-tag#203]
- [x] Drop support for Node.js 10 and 12 - resolved #186
- [x] Support Node.js 16 and 18 - resolved #171 and #197
- [x] Migrate from AVA to Vitest - resolved #200
- [ ] Update or migrate `cac` package

    Unable to update `cac` package due to [changing help messages](https://github.com/sounisi5011/package-version-git-tag/blob/96cf4d805a0be1ee56affb993888010efdd24cd9/.renovaterc.json5#L64-L71).
    Update the `cac` package and introduce breaking changes, or switch to another package.

- [ ] Move from CommonJS to ESM

    [Some dependencies moved to pure ESM](https://github.com/sounisi5011/package-version-git-tag/blob/96cf4d805a0be1ee56affb993888010efdd24cd9/.renovaterc.json5#L72-L87).
    However, this CLI is not yet a pure ESM and cannot update these dependencies.

    The primary use of this CLI is in the release process, so there is no need to support the old Node.js.
    Therefore, it should be possible migrate to a pure ESM.

- [ ] Remove [`release` scripts](https://github.com/sounisi5011/package-version-git-tag/blob/96cf4d805a0be1ee56affb993888010efdd24cd9/package.json#L46-L54) and use GitHub Actions for automatic releases

    [Package `is-git-status-clean` in the dependencies](https://github.com/sounisi5011/package-version-git-tag/blob/96cf4d805a0be1ee56affb993888010efdd24cd9/package.json#L88) depends on package `trim-newlines@^2.0.0` with [known vulnerabilities](https://github.com/advisories/GHSA-7p7h-4mm5-852v).
    However, this package is only used for manual releases.
    If releases are automated, this dependency is not needed.
    The release process should be automated, not only to remove vulnerable dependencies, but also to prevent human error.
